Use FQDN for hostname
antoineco/aco-yum_autoupdate pull request #13
Opened 2016-04-28 15:02 UTC by jcpunk

Since the system name is already known, we may as well set it.

2016-07-29 15:22 UTC, antoineco commented
Would it not make more sense to let the user decide whether he wants to set it or not, and make the value configurable?

Something like https://github.com/antoineco/aco-tomcat/blob/master/templates/common/setenv.erb#L5

note: `SYSTEMNAME` defaults to `$(hostname)`

2017-06-06 19:22 UTC, jcpunk commented
I finally got back around to this one

2017-06-07 09:14 UTC, antoineco requested changes
Thanks @jcpunk! I requested a few changes which are mininal. You can ignore the warnings from Travis, I'll take care of that before releasing your changes :+1:

2017-06-07 09:14 UTC, antoineco commented on manifests/init.pp
> +  $systemname          = '',
I'd rather default to `undef`, which is more idiomatic.

2017-06-07 09:14 UTC, antoineco commented on manifests/init.pp
> +  if $systemname { validate_string($systemname) }
The `validate_*` functions are deprecated, besides we want to accept the `undef` value (see previous comment) so you can actually get rid of this.

2017-06-07 09:14 UTC, antoineco commented on README.md
> +Hostname to use for identification. Defaults to '' which should be automatically converted to the system hostname.
Since `undef` is a better default (see below) you can replace the second sentence with *"Defaults to the system hostname if undefined"*.

2017-06-07 13:55 UTC, jcpunk commented
I think I've got the changes made and squashed down to a single commit.

2017-06-07 14:34 UTC, merged

2017-06-07 14:34 UTC, antoineco commented
Thanks @jcpunk!

2017-06-07 20:10 UTC, antoineco commented
Released in v0.6.4.